site_name: cu-astr3510
site_url: https://zkbt.github.com/cu-astr3510
nav:
    - index.md
    - installation.ipynb
    - Basics:
      - basics/plots.ipynb
      - basics/units.ipynb
      - basics/fits-files.ipynb
      - basics/color-images.ipynb
    - Concepts:
      - concepts/catching-photons.ipynb
      - concepts/chi-squared-fitting.ipynb
      - concepts/psfs/psfs.ipynb
    - Tools:
      - tools/gaia.ipynb
    - reference.md

theme:
  name: "material"
  features:
      - navigation.tracking
repo_url: https://github.com/zkbt/cu-astr3510/
plugins:
  - search
  - mkdocs-jupyter:
      execute : True
      include_source : True
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../astr3510]
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: True
            show_root_heading: True
            show_root_toc_entry: False
            show_root_full_path: False
            show_category_heading: False
            show_submodules: False
            merge_init_into_class: False
            show_if_no_docstring: False
            heading_level: 3
            show_bases: False
      custom_templates: templates
      watch:
        - astr3510
markdown_extensions:
    - toc:
        permalink: "#"

# this is super borrowed from Christina Hedges' fabulous
# https://christinahedges.github.io/astronomy_workflow/
